apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fullstack
spec:
  selector:
    app: backend
  ports:
    - port: 5000       # cluster-internal port
      targetPort: 5000 # container port
  type: NodePort     # internal-only, perfect for frontend to reach backend